version: '3'
services:
  rails-api:
    build: ./rails_api
    volumes:
      - ./rails_api:/app
    ports:
      - "3000:3000"
    command: rails server -b '0.0.0.0' -p '3000'

  react-app:
    build: ./react_frontend
    volumes:
      - ./react_frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

