version: '3'
services:
  backend:
    build: ./rails_api
    ports:
      - "3000:3000"
  frontend:
    build: ./react_frontend
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
