swagger: '2.0'
info:
  version: '1.0'
  title: Product API

paths:
  /api/product:
    get:
      tags:
        - Product
      summary: List all products
      responses:
        '200':
          description: A list of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      tags:
      - Product
      summary: Create a new product
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '201':
          description: Product created
          schema:
            $ref: '#/definitions/Product'
        '422':
          description: Validation error
  /api/product/{id}:
    get:
      tags:
        - Product
      summary: Get a specific product by id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: A product
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: Product not found
    put:
      tags:
        - Product
      summary: Update a product
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: Product updated
          schema:
            $ref: '#/definitions/Product'
        '404':
          description: Product not found
        '422':
          description: Validation error
    delete:
      tags:
        - Product
      summary: Delete a product
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found

definitions:
  Product:
    type: object
    required:
      - productId
      - productName
      - productOwnerName
      - scrumMasterName
    properties:
      productId:
        type: integer
        description: Must be unique
      productName:
        type: string
      productOwnerName:
        type: string
      scrumMasterName:
        type: string
      Developers:
        type: array
        items:
          type: string
        description: Must be an array of strings and not empty and less or equal to 5 strings
      startDate:
        type: string
        format: date
        description: Must be a valid date in the format YYYY-MM-DD
      methodology:
        type: string
        enum: [Agile, Waterfall]
        description: Methodology should be either Agile or Waterfall
      location:
        type: string
